virtual-kubelet/virtual-kubelet

README.md, cmd/root.go, cmd/version.go
- Remove toggle flag
- Update version message
- Update README.md with new changes
=> Cleaning up program UX

cmd/root.go
Just fixing a small typo in one of the args descriptions
=> Fixed small typo in arg description

Gopkg.lock, Gopkg.toml, README.md, charts/virtual-kubelet/templates/deployment.yaml, charts/virtual-kubelet/templates/secrets.yaml, charts/virtual-kubelet/values.yaml, cmd/root.go, examples/nginx-pod.yaml, providers/azure/aci.go, providers/azure/client/aci/client_test.go, providers/azure/client/aci/get.go, providers/hypersh/hypersh.go, scripts/createCertAndKey.sh, vkubelet/apiserver.go, vkubelet/provider.go, vkubelet/vkubelet.go
=> Enable kubectl logs

providers/azure/README.md
updated so it's consistent with the updates in the cli
=> updating azure readme

Gopkg.lock, providers/azure/aci.go, providers/azure/client/aci/types.go, vendor/github.com/cenkalti/backoff/.gitignore, vendor/github.com/cenkalti/backoff/.travis.yml, vendor/github.com/cenkalti/backoff/LICENSE, vendor/github.com/cenkalti/backoff/README.md, vendor/github.com/cenkalti/backoff/backoff.go, vendor/github.com/cenkalti/backoff/backoff_test.go, vendor/github.com/cenkalti/backoff/context.go, vendor/github.com/cenkalti/backoff/context_test.go, vendor/github.com/cenkalti/backoff/example_test.go, vendor/github.com/cenkalti/backoff/exponential.go, vendor/github.com/cenkalti/backoff/exponential_test.go, vendor/github.com/cenkalti/backoff/retry.go, vendor/github.com/cenkalti/backoff/retry_test.go, vendor/github.com/cenkalti/backoff/ticker.go, vendor/github.com/cenkalti/backoff/ticker_test.go, vendor/github.com/cenkalti/backoff/tries.go, vendor/github.com/cenkalti/backoff/tries_test.go
Fix: https://github.com/virtual-kubelet/virtual-kubelet/issues/64
Add the missing vendor package.
=> Fix the EmptyDir Volume Error in ACI Provider

providers/azure/aci.go, vkubelet/vkubelet.go
Fixing issue: https://github.com/virtual-kubelet/virtual-kubelet/issues/40
Also fixing another small bug when kubelet port is not specified in env var. It will use the default port now.
=> [Azure] Filters service account secret volume mount for Windows

providers/azure/aci.go
=> Fix the ImagePullSecret for ACI Provider

providers/mock/mock.go, vkubelet/vkubelet.go
I thought it would be a great idea to write a mock provider.
That way running Kubernetes as a dependency in a pipeline like CircleCI becomes trivial.
This is a super rough bit of code, but I wanted to create this ticket and see if others were interested in this provider.
=> Provider: Mock

providers/azure/aci.go
Fix for https://github.com/virtual-kubelet/virtual-kubelet/issues/87
=> [Azure] Append args after command

providers/mock/mock.go
=> Provide method to correctly build Key from names in the mock provider

examples/nanoserver.yaml, examples/nginx-pod.yaml
adding nanoserver image b/c iis doesn't work w/ ACI. 
ACI does not support any images with windowserver 1709
=> add nanoserver

README.md
Changed the CLA from Microsoft to CNCF. Also updated the code of conduct! 
#110
=> change cla to cncf

examples/iis-pod.yaml
Fix the merge conflict in the examples
Add back the iis example
=> Fix the examples

providers/azure/aci.go
Fixes #119.
Handles both dockercfg format and dockerconfigjson formats for image pull secrets.
=> Handling dockerconfigjson format for image pull secrets

examples/iis-pod.yaml, examples/nanoserver.yaml
Remove the resources field in the nanoserver.yaml to use the default value
Add the resources.limits field in the iis-pod.yaml.
=> Update the resources field in the exmaples

AUTHORS, CONTRIBUTING.md, ISSUE_TEMPLATE.md, README.md
* Add Fargate maintainer information
* Update docs to use CNCF CLA and code of conduct
* Remove dead link to review.md
=> Update Fargate maintainer info

Makefile
Fixes https://github.com/virtual-kubelet/virtual-kubelet/issues/190.
```console
$ make clean
Clean...
```
=> Fix 'make clean'

LICENSE
changing the license using the git template
=> update license to apache 2.0

vkubelet/vkubelet.go
Fix #151 #152 #222 
If the connection to api server is not reliable, the VK container will exit and rely on the pod to restart the container.  If it happens frequently, VK pod will get into CrashLoopBackoff state. Because of the backoff, there is a chance that the VK pod didn't start in time to update the node status before the controller manager removes the VK node from the api server.
The fix is to add an extra loop to handle the pod watcher unexpected close issue.
=> [VK] Add an extra loop when the pod watcher is closed unexpectedly.

vkubelet/vkubelet.go
=> [VK] Do not Sync ProviderFailed Pod Status

providers/aws/fargate/cluster.go
Handle failures due to missing clusters explicitly.
=> Fargate: Improve cluster API failure handling

providers/mock/mock.go, vkubelet/vkubelet.go
=> config files for mock provider

vkubelet/vkubelet.go
If, for some reason, the VK pod cannot reach out to the API server for a period of time (~1 minute), the VK node will be removed from the API server by the node controller. Even the VK pod is able to connect to the API server again, it will still fail to update the node status, nor register the node.
The fix is to re-register the node in such case.
@erikstmartin
=> [VK] Register the Node when GetNode Returns NotFound

providers/aws/README.md
Added a link to AWS open source virtual-kubelet blog post to README.
=> Fargate: Add AWS open source blog post to README

providers/azure/client/aci/client.go, providers/azure/client/aci/client_test.go, providers/azure/client/aci/types.go
Updating aci sdk to add network profile bits
=> Adding network policy reference

providers/azure/client/aci/client_test.go, providers/azure/client/aci/types.go, scripts/createCredentials.sh
This PR exposes the Log Analytics SDK for the ACI provider
=> add support for log analytics in the ACI SDK

.gitignore, charts/virtual-kubelet/templates/deployment.yaml, charts/virtual-kubelet/templates/secrets.yaml, charts/virtual-kubelet/values.yaml, providers/azure/aci.go, providers/azure/client/README.md, providers/azure/client/aci/analytics.go, providers/azure/client/aci/analytics_test.go, providers/azure/client/aci/client_test.go
This PR adds the ability to specify a log analytics workspace key and ID
=> Plumb through log analytics values

providers/aws/config.go, providers/aws/fargate/container.go, providers/aws/fargate/container_test.go, providers/aws/provider.go, providers/aws/provider_test.go
AWS Fargate provider:
* Adds environment variable support
* Adds stubs (errNotImplemented) to new provider APIs
Fixes #273
=> Add environment variable support to AWS Fargate provider

providers/azure/README.md
=> adding the taint format

providers/hypersh/hypersh.go, vkubelet/vkubelet.go
Fix hypersh provider issue #324 
Fix vkubelet updateNode failed after re-register the node.
=> Bug Fixes: Hypersh throw expection and error in updateNode

providers/azure/aci.go, providers/azure/aci_test.go
Hash the container group resource ID + container name and set it to the ContainerStatus.ContainerID.
=> Add ContainerID into the ContainerStatus

providers/azure/client/network/client.go
Update the NRP api-version to 2018-07-01
=> Update the network api version

providers/azure/aci.go
=> Fix the pod uuid

providers/azure/aci.go, providers/azure/client/aci/get.go
`resp` is nil when `Do()` has an error.
Also seems there was some gofmt issues in the file.
=> Fix NPE panic in ACI client

Gopkg.lock, vendor/github.com/cpuguy83/strongerrors/LICENSE, vendor/github.com/cpuguy83/strongerrors/defs.go, vendor/github.com/cpuguy83/strongerrors/doc.go, vendor/github.com/cpuguy83/strongerrors/helpers.go, vendor/github.com/cpuguy83/strongerrors/is.go, vendor/github.com/cpuguy83/strongerrors/status/grpc.go, vendor/github.com/cpuguy83/strongerrors/status/http.go, vkubelet/api/exec.go, vkubelet/api/helpers.go, vkubelet/api/logs.go, vkubelet/api/stats.go, vkubelet/apiserver.go, vkubelet/provider.go
- Remove intermediate API server objects
- Instrustment handlers for logging/error handling
Overall this makes it much cleaner/simpler to add more instrumentation, including tracing and metrics.
=> Refactor http handlers

.circleci/config.yml, .golangci.yml
Adds a CI job for linting code.
Only lints for new code being added by a PR (because there's lots of problems that need to be fixed in the existing codebase).
=> Add linters to CI

manager/resource.go, vkubelet/vkubelet.go
Set the pod phase based on pod restart policy when provider failed.
Update the resource manager to include the deleting pods in the GetPods function.
This change can avoid the deployment spin up pods when the provider failed to create the pod.
Fix #105 #78
=> [VK] Set the pod phase based on pod restart policy when provider failed

cmd/root.go
use logrus.SetLevel to set the log level.
=> [VK] Set the log level correctly

providers/azure/metrics_test.go
The multi-container test is not robust as the sequence of the container is not guaranteed. Change to compare the containers regardless of the order.
=> [ACI] Make the metrics test more robust in multi-container case

vkubelet/pod.go
We need to expect cache.DeletedFinalStateUnknown type in the OnDelete function. [reference](https://github.com/kubernetes/client-go/blob/80f980e507e36cabebdbedc628496c4d19c3af2c/tools/cache/controller.go#L173-L176)
=> [VK] Fix the potential runtime type casting error

providers/register/provider_alicloud.go
=> Typo in build tag for alicloud provider

providers/azure/aci.go, providers/azure/aciMock.go, providers/azure/aci_test.go, providers/azure/client/aci/analytics.go, providers/azure/client/aci/client.go, providers/azure/client/aci/client_test.go, providers/azure/client/aci/exec.go, providers/azure/client/aci/get.go, providers/azure/client/aci/rp.go, providers/azure/client/aci/rp_test.go, providers/azure/client/aci/types.go
Add GPU support for ACI provider. It's in private preview.
=> [ACI] GPU Support

README.md
*edited by @pires for auto-closing.*
Fixes #49
=> Update docs for how to add a provider

vkubelet/pod.go
This uses the same number of workers as the pod sync workers.
We may want to start a worker queue here instead, but I think for now
this is ok, particularly because we are limiting the number of
goroutines being spun up at once.
=> Make pod status updates concurrent.

vkubelet/vkubelet.go
Otherwise this ticker could run forever (or until the process exits).
=> Ensure reconcile ticker stops on shutdown

providers/azure/README.md
Adding document links to our official Azure docs
=> adding virtual node docs

vkubelet/vkubelet.go
Tickers always tick, so if we tick every 5 seconds and the work that we
perform at each tick takes 5 seconds, we end up just looping with no
sleep period.
Instead this is using a timer to ensure we actually get a full 5 second
sleep between loops.
We should consider an async API instead of polling the provider like
this.(https://github.com/virtual-kubelet/virtual-kubelet/issues/476)
=> Use timer instead of ticker

providers/azurebatch/README.md
Signed-off-by: zhangyue <zy675793960@yeah.net>
README.MD -> README.md
=> fix: fix dead link

vkubelet/env.go, vkubelet/env_internal_test.go
=> env: fix resource reference Optional nil pointer

Gopkg.lock, vendor/golang.org/x/crypto/blake2b/blake2b.go, vendor/golang.org/x/crypto/blake2b/blake2bAVX2_amd64.go, vendor/golang.org/x/crypto/blake2b/blake2bAVX2_amd64.s, vendor/golang.org/x/crypto/blake2b/blake2b_amd64.go, vendor/golang.org/x/crypto/blake2b/blake2b_amd64.s, vendor/golang.org/x/crypto/blake2b/blake2x.go, vendor/golang.org/x/crypto/internal/subtle/aliasing.go, vendor/golang.org/x/crypto/internal/subtle/aliasing_appengine.go, vendor/golang.org/x/crypto/nacl/secretbox/secretbox.go, vendor/golang.org/x/crypto/poly1305/sum_noasm.go, vendor/golang.org/x/crypto/poly1305/sum_ref.go, vendor/golang.org/x/crypto/poly1305/sum_s390x.go, vendor/golang.org/x/crypto/poly1305/sum_s390x.s, vendor/golang.org/x/crypto/poly1305/sum_vmsl_s390x.s, vendor/golang.org/x/crypto/ssh/terminal/util.go, vendor/golang.org/x/crypto/ssh/terminal/util_aix.go, vendor/golang.org/x/crypto/ssh/terminal/util_plan9.go, vendor/golang.org/x/crypto/ssh/terminal/util_solaris.go, vendor/golang.org/x/crypto/ssh/terminal/util_windows.go, vendor/golang.org/x/sys/cpu/cpu.go, vendor/golang.org/x/sys/cpu/cpu_arm.go, vendor/golang.org/x/sys/cpu/cpu_arm64.go, vendor/golang.org/x/sys/cpu/cpu_mips64x.go, vendor/golang.org/x/sys/cpu/cpu_mipsx.go, vendor/golang.org/x/sys/cpu/cpu_ppc64x.go, vendor/golang.org/x/sys/cpu/cpu_s390x.go, vendor/golang.org/x/sys/cpu/cpu_x86.go, vendor/golang.org/x/sys/cpu/cpu_x86.s
This fixes master build for certain CPU's.
See https://github.com/golang/crypto/commit/ae8bce0
=> Bump crypto package.

website/config.toml, website/data/providers.yaml
This PR adds the recently created Nomad provider to the website.
=> Add Nomad provider to website

providers/azure/README.md
Fixed the chart url issues
Added more variables
Tested on acs-engine for accuracy
=> ACI docs & limitations

netlify.toml, website/assets/sass/style.sass, website/config.toml, website/layouts/_default/baseof.html, website/layouts/index.html, website/layouts/partials/css.html, website/layouts/partials/docs/header.html, website/layouts/partials/docs/sidebar.html, website/layouts/partials/footer.html, website/layouts/partials/home/hero.html, website/layouts/partials/home/info.html, website/layouts/partials/home/social.html, website/layouts/partials/javascript.html, website/layouts/partials/meta.html, website/layouts/partials/navbar.html, website/layouts/shortcodes/providers.html, website/layouts/shortcodes/svg.html
This PR adds the standard bits of SEO metadata to the site, including OpenGraph and Twitter Card parameters.
=> Add SEO metadata to website

Makefile, cmd/providers.go, cmd/root.go, cmd/version.go, providers/register/provider_alibabacloud.go, providers/register/provider_aws.go, providers/register/provider_azure.go, providers/register/provider_azurebatch.go, providers/register/provider_cri.go, providers/register/provider_huawei.go, providers/register/provider_mock.go, providers/register/provider_nomad.go, providers/register/provider_sfmesh.go, providers/register/provider_vic.go, providers/register/provider_web.go, providers/register/register.go, scripts/process_build_tags.sh
Flip the boolean for provider build tags.
Also adds a sub-command to check which providers are compiled in.
=> Support building an allow-list of providers

providers/azure/README.md
Ria, Vipin, Brian can you review these changes?
=> ACI readme updates

cmd/root.go, manager/resource.go, manager/resource_test.go, providers/azure/aci_test.go, test/util/kubernetes.go, test/util/resource_manager.go
This will be used to set up env var for services within VK similar to what we do for configmaps and secrets.
=> Resource manager: add service lister and remove unused lock.

Gopkg.lock, manager/resource_test.go, test/e2e/framework/pod.go, test/util/kubernetes.go, vendor/k8s.io/kubernetes/pkg/apis/core/helper/helpers.go, vendor/k8s.io/kubernetes/pkg/apis/core/v1/helper/helpers.go, vendor/k8s.io/kubernetes/pkg/kubelet/envvars/doc.go, vendor/k8s.io/kubernetes/pkg/kubelet/envvars/envvars.go, vkubelet/env.go, vkubelet/env_internal_test.go
This change introduces setting container env var using services.
It also adds tests for the same.
=> Set container env var using services.

Makefile
As discussed with @sargun, I extracted this fix out of the #514.
ping @sargun
=> Makefile: fix gobin path

vkubelet/pod_test.go
Don't use actual "mock" provider in vkubelet to reduce awkward import
cycles.
Really the "mock" provider is for e2e tests. Instead create our own mock
in the vkubelet package specifically for unit tests which can also be
more easily customized to test edge cases.
Closes #632
=> Use custom mock in vkubelet tests

cmd/virtual-kubelet/commands/root/root.go, vkubelet/node.go, vkubelet/node_test.go
Do not enable leases by default in the node constructor.
Simplify node constructor to not require a lease client when leases may
not even be enabled.
Updates node status update interval to the kubelet default of 10s (was
5s in vk).
Closes #652
=> Update node defaults

cmd/virtual-kubelet/commands/root/tracing_register.go, cmd/virtual-kubelet/commands/root/tracing_register_jaeger.go, cmd/virtual-kubelet/commands/root/tracing_register_ocagent.go, cmd/virtual-kubelet/commands/root/tracing_register_test.go, cmd/virtual-kubelet/main.go, log/logrus/logrus.go, log/logrus/logrus_test.go, log/nop.go, manager/doc.go, manager/resource.go, manager/resource_test.go, node/api/doc.go, node/api/exec.go, node/api/helpers.go, node/api/logs.go, node/api/pods.go, node/api/server.go, node/api/stats.go, node/doc.go, node/env.go, node/env_internal_test.go, node/node.go, node/node_test.go, node/pod.go, node/pod_test.go, node/queue.go, trace/nop.go, trace/opencensus/opencensus.go, trace/opencensus/opencensus_test.go, trace/trace.go
Realized as I was starting to copy some stuff to other repos that we
should go ahead and add this.
=> Add authors to file heads

cmd/virtual-kubelet/commands/root/root.go, node/podcontroller.go
We'll need these informers for
https://github.com/virtual-kubelet/virtual-kubelet/pull/586
Changing this now means we don't need to make API changes later.
=> Use object informers instead of listers

node/pod.go
A legit error could be passed here and we don't want to ignore it.
=> Don't ignore all GetPod errors on deletePod

.circleci/config.yml, Makefile.e2e, hack/skaffold/virtual-kubelet/skaffold.yml
@cpuguy83 I have some misc improvements that I'd like to include in whatever solution you come up with for #693. Hopefully, you can do it as part of this PR?
=> e2e: misc improvements

Makefile.e2e
@cpuguy83 for some reason I didn't include this in #695 🤦‍♂
=> e2e: cleanup after run

cmd/virtual-kubelet/internal/commands/providers/provider.go, cmd/virtual-kubelet/internal/commands/root/tracing_register.go, doc.go, log/log.go, node/doc.go, node/podcontroller.go, trace/trace.go
Signed-off-by: zhuangqh <zhuangqhc@gmail.com>
=> fix several typo

go.mod, go.sum, node/lifecycle_test.go, node/mock_test.go, node/pod_test.go
This uses the mock provider, so I moved the mock provider to a
location where the node test can use it.
=> Add a test which tests the e2e lifecycle of the pod controller

node/pod.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
=> cleanup: fix misspelled words in error message

node/node.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
=> cleanup: fix some typos in node.go

node/lifecycle_test.go
If the informers are starting at the same time as createPods,
then we can get into a situation where the pod seems to get
"lost". Instead, we wait for the informer to get into sync
prior to the createpod event.
This also moves to one informer as a microoptimization in
the tests.
=> Wait for the informer to become in sync before starting tests

node/lifecycle_test.go
All updates in our tests should have the behaviour that best
reflects what API server does.
=> Add a generic reactor to lifecycle_test to bump resource version

errdefs/doc.go
Signed-off-by: 928234269 <longfei.shang@daocloud.io>
=> fix tyop in doc.go

node/mock_test.go
This fixes the "leak" we had in the mock provider
=> Fix mock_test DeletePod to store updated pod status

node/podcontroller.go
This moves the event handler registration until after the cache
is in-sync.
It makes it so we can use the log object from the context,
rather than having to use the global logger
The cache race condition of the cache starting while the reactor
is being added wont exist because we wait for the cache
to startup / go in sync prior to adding it.
=> Move location of eventhandler registration

README.md, node/pod_test.go, node/queue.go
This PR adds unit tests for changes made in #584.  It also fixes two small typos in the codebase.
=> Add unit tests for #584

cmd/virtual-kubelet/internal/commands/root/tracing_register.go, node/env_internal_test.go, node/pod_test.go
fix lint warnings reported by
* gofmt
* misspell
=> fix lint warnings

node/lifecycle_test.go
If a pod is being gracefully deleted at podcontroller startup,
it will not get deleted via the deletedanglingpods code. This
ensures the normal deletion loop covers the case.
=> Ensure that if VK starts up, and a pod has deletiontimestamp set, the deletion is propagated to the provider

node/node.go, node/node_test.go
If the ping timer is being used, it should be reset with the ping update
interval. If the status update interval is used then Ping stops being
called for long enough to cause kubernetes to mark the node as NotReady.
Fixes #788
=> After handling status update, reset update timer with correct duration

ADOPTERS.md, README.md, website/data/providers.yaml, website/layouts/partials/home/info.html, website/layouts/shortcodes/providers.html
=> add provider admiralty multi-cluster scheduler

README.md
Changing VK meeting times to be once a month, and to be held as office hours. 
Changed from bi-monthly Wednesday meetings at 10:30 to once a month on Thursday at 10am.
=> Changing meeting times

ADOPTERS.md, README.md, website/data/providers.yaml
I added our provider to the README and to the list on the website.
=> Add Elotl Kip as a provider

website/content/docs/setup.md
add `cd virtual-kubelet` for convenience
Signed-off-by: EDGsheryl <edgsheryl@gmail.com>
=> Optimize Docs

node/api/logs.go, node/api/logs_test.go
Check if "follow" is requested for container logs, and pass it to the
provider so tailing logs can be supported.
=> Add support for v1.PodLogOptions

node/pod.go
dedup in updatePodStatus as mentioned in https://github.com/virtual-kubelet/virtual-kubelet/pull/824#discussion_r411047984
=> dedup in updatePodStatus

README.md
Edit zoom link since we have a new cncf vk zoom account.
=> Zoom link update

node/node.go
This adds tracing in node controller in several sections where
it was missing.
=> Add instrumentation to node controller (tracing)

ADOPTERS.md
In [Tencent Games](https://game.qq.com/), we use `virtual-kubelet` for multiple kubernetes clusters management. And we create the open source project [tensile-kube](https://github.com/virtual-kubelet/tensile-kube).
=> Add Tencent Games to the adopters

README.md
=> Add tensile kube to README

website/data/providers.yaml
Sorry, I forget to add it to the website in the last [PR](https://github.com/virtual-kubelet/virtual-kubelet/pull/848)
PTAL @cpuguy83
=> Add tensile kube to website

README.md
=> Rearange OpenStack/Tensile Part

node/node.go, node/node_test.go
This sets / updates the node lease owner reference to the current
node. Previously, we did not set this, which had the interesting
problem of leaking node leases on clusters with node churn.
=> Set Node Leader Owner Reference

README.md
close #419 
Adds link to VK dev mailing list
Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>
=> docs(README): Add link to mailing list

go.mod, internal/podutils/env.go
This tries to do a slightly more gradual refactoring of the code in env.go. And split the changes into multiple commits.
=> Refactor env.go

Makefile
The whole $Q thing is unintuitive and that's not how Makefiles
typically act. It's confusing.
=> Remove $Q Makefile command surpression

node/pod.go
More context [here](https://github.com/virtual-kubelet/virtual-kubelet/issues/399#issuecomment-704186791).
Closes #399
Signed-off-by: Hasan Turken <turkenh@gmail.com>
=> Don't skip pods status update if provider failed once but recovered with retry

node/pod.go, node/pod_test.go
If the provider is K8s provider. Pod may be evicted when node is not ready. But the eviction would failed because `node not ready`. If the Pod is created by a workload e.g. deployment or statefulSet we should re-create the Pod.
In the PR, we add logic about checking DeletingTimeStamp in a Provider, which enables Providers to cover `node not ready`  issue
=> Allow to update pod status in K8s if it is deleting in Provider

.golangci.yml, cmd/virtual-kubelet/internal/provider/mock/mock.go, node/node.go
This also adds a bunch of nolints for the node package which
has a ton of stuttering. Perhaps something to mitigate in another
iteration.
=> Add Stutter linter

node/pod.go, node/podcontroller.go
As described in the issue, if the following sequence happens, we fail to properly
update the pod status in api server:
1. Create pod in k8s
2. Provider creates the pod and syncs its status back
3. Pod in k8s ready/running, all fine
4. Virtual kubelet fails to update node status for some time for whatever reason (e.g. network connectivity issues)
5. Virtual node marked as NotReady with message: Kubelet stopped posting node status
6. kube-controller-manager of k8s, goes and marks all pods as Ready = false:
7. Virtual kubelet never sync's status of pod in provider back to k8s
=> Fix issue #899: Pod status out of sync

.circleci/config.yml, hack/skaffold/virtual-kubelet/skaffold.yml, test/e2e/README.md
Also bumped minikube and skaffold.
=> e2e: test with Kubernetes to 1.20.1

.golangci.yml, go.mod, internal/kubernetes/README.md, internal/kubernetes/remotecommand/exec.go, internal/kubernetes/remotecommand/httpstream.go, internal/kubernetes/remotecommand/websocket.go, node/api/exec.go
Copy/paste some more kubernetes code. This is to remove the dep on
kubernetes/kubernetes from within exec.go
See #940
Signed-off-by: Miek Gieben <miek@miek.nl>
=> Import kubernetes/remotecommand

log/klogv2/klogv2.go
I feel so dumb, right now. Sorry, folks!
Well, at least @cpuguy83 didn't get the new release out :D
=> log: fix klogv2.WithField(s)

node/pod.go, node/pod_test.go, node/podcontroller.go
=> Fix race between k8s and provider when deleting pod

internal/expansion/expand_test.go, internal/podutils/env.go, internal/test/e2e/framework/pod.go, node/api/exec.go
These are all simple changes that will not change w/o breaking API
changes upstream anyway.
=> Don't import pod util package from k/k

README.md
mention `GetStatsSummary ` if someone want to use hpa
=> Add scrape pod metrics

cmd/virtual-kubelet/internal/commands/root/root.go
I run into this during some testing. After implementing a fix, I realized there was a longstanding PR but it is blocked by the CLA and there hasn't been any response to Brian's request for the CLA to be signed.
Closes #1000.
=> cmd: fix nil pointer during node setup

cmd/virtual-kubelet/internal/provider/mock/mock.go, internal/test/e2e/framework/stats.go, node/api/metrics.go, node/api/server.go, node/nodeutil/provider.go, test/e2e/basic.go
Added handlers for `/metrics/resource` endpoint
Refs #1075 
Closes #987
=> feat: Implement new metrics endpoint for k8s 1.24+

cmd/virtual-kubelet/internal/provider/mock/mock.go
Extend mock provider to support advance capacity settings such as hugepage, SRIOV resources and providerID.
Fixes: #1086
Use the following provider configuration file:
```
{
"vkubelet-mock-0": {
"cpu": "18",
"memory": "80Gi",
"others": {
"hugepages-1Gi": "24Gi",
"hugepages-2Mi": "1024Mi",
"intel.com/sriov-igb-uio": "3",
"intel.com/sriov-vfio-pci": "4"
},
"providerID": "mock://4218ae82-4789-afeb-b767-19948fd69eb3"
}
}
```
Run virtual-kubelet using the above configuration file and finally the mock node has the corresponding capacity and providerID.
```
[ ~/vk ]# kubectl describe node vkubelet-mock-0
...
Capacity:
cpu:                          18
hugepages-1Gi:                24Gi
hugepages-2Mi:                1Gi
intel.com/sriov-igb-uio:      3
intel.com/sriov-vfio-pci:     4 
memory: …
```
=> Extend mock provider to support extra node capacity settings and providerID

.github/workflows/ci.yml, go.mod, node/api/metrics_test.go
since k/k upstream has upgraded to 1.19 already
=> chore: bump golang version to 1.19

website/data/providers.yaml
Requesting to add a new provider to the list of providers for Stackpath Edge compute platform
=> Add Stackpath provider

website/data/providers.yaml
Fixing a typo in the name: Stackpath --> StackPath
@helayoty
=> Update providers.yaml  - StackPath
