- providers/hypersh/util.go
This fixes issue #46 
When the hyper config file is not set, the AuthConfig should be empty to avoid a crash.
> If the hyper config file is not set, the AuthConfig should be empty

- .gitignore
- providers/web/broker.go
- providers/web/charts/virtual-kubelet-web/.helmignore
- providers/web/charts/virtual-kubelet-web/Chart.yaml
- providers/web/charts/virtual-kubelet-web/templates/NOTES.txt
- providers/web/charts/virtual-kubelet-web/templates/_helpers.tpl
- providers/web/charts/virtual-kubelet-web/templates/deployment.yaml
- providers/web/charts/virtual-kubelet-web/values.yaml
- providers/web/rust-web-provider/.gitignore
- providers/web/rust-web-provider/Cargo.lock
- providers/web/rust-web-provider/Cargo.toml
- providers/web/rust-web-provider/Dockerfile
- providers/web/rust-web-provider/scripts/buildDocker.sh
- providers/web/rust-web-provider/src/main.rs
- providers/web/rust-web-provider/src/unit_provider.rs
- providers/web/rust-web-provider/src/utils.rs
- vkubelet/provider.go
- vkubelet/vkubelet.go
This PR is mainly just an exploration of an idea - part of a spike we are exploring in Azure IoT Edge to see if we can integrate Azure IoT Edge deployments via virtual kubelet. As part of that we implemented a "web" provider for virtual kubelet that essentially proxies requests to a web endpoint. The point of this is to enable the writing of virtual kubelet providers in any arbitrary technology stack (as it happens we need our provider to be written in .NET Core).
The PR includes:
- the web broker provider in `providers/web/broker.go` that does the request proxying
- a sample provider written in Rust that lives in `providers/web/rust-web-provider`; this sample simply saves the pod deployments in an in-memory data structure
- a helm chart that deploys both the virtual kubelet and the Rust …
> Implement web broker provider and a sample provider in Rust

- README.md
- providers/azure/aci.go
- providers/hypersh/hypersh.go
- providers/web/broker.go
- vkubelet/provider.go
This seems to be a common typo, possibly exacerbated by copy-paste of comment strings. I spotted it in the README.md at first, so I fixed that and then checked the rest of the code and fixed a few more. They are all in comments or documentation, so there's no code issue.
FYI, there's still some in the vendor directory, but I haven't fixed those as they'd get replaced by any new `go get` I think:
```
$ ack uberentes
vendor/k8s.io/apimachinery/hack/godep-deps.sh
20:# 2. godep restore based on k8s.io/kuberentes provided manifest
vendor/k8s.io/client-go/CHANGELOG.md
120:* Included bug fixes in k8s.io/kuberentes release-1.5 branch, up to
vendor/k8s.io/client-go/kubernetes/fake/register.go
64://     clientsetscheme "k8s.io/client-go/kuberentes/scheme" …
```
> Correct typo kuberentes->kubernetes

- providers/azure/example.toml
When not having quotes, I ran into the following errors:
* 2018/01/17 16:33:14 Near line 7 (last key parsed ''): expected a top-level item to end with a newline, comment, or EOF, but got 'G' instead
* 2018/01/17 16:41:20 toml: cannot load TOML value of type int64 into a Go string
> Add quotes for azure example.toml

- README.md
- vkubelet/vkubelet.go
I added a README section to detail the workaround enabling node exclusion for services for k8s 1.9 clusters. Not entirely confident if this an appropriate place for it, but seems like it should be documented anyway … :)
Additionally, I noted that the node exclusion label itself was added to the annotations metadata, when it should have been added to the labels metadata, so that was changed as well. 
Fixes #41 for k8s 1.9 clusters with `ServiceNodeExclusion` enabled
> Node exclusion to labels, adding README section

- examples/iis-pod.yaml
There shouldn't be a nodename selector. That prevents it from working in recent builds configured with `az aks install-connector`
> Fix scheduling for Windows example

- README.md
- providers/azure/aci.go
Based on the region availability for ACI (https://docs.microsoft.com/en-us/azure/container-instances/container-instances-quotas#region-availability), I made the following changes to make sure we only deploy ACI instances where it's supported. Fixes (avoids?) #91. 
Error message when using `westus2`:
```
$ helm install charts/virtual-kubelet -f values-linux-19.yaml
NAME:   fun-cheetah
LAST DEPLOYED: Sat Feb 10 12:04:10 2018
NAMESPACE: default
STATUS: DEPLOYED
RESOURCES:
==> v1/Secret
NAME                         TYPE    DATA  AGE
fun-cheetah-virtual-kubelet  Opaque  3     3s
==> v1beta1/Deployment
NAME                         DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
fun-cheetah-virtual-kubelet  1        1        1           0          3s
==> v1/Pod(related)
NAME …
```
> Adding supported regions for Azure Provider

- README.md
- providers/azure/README.md
It took me a while to figure everything out in order to successfully registered an ACI virtual-kubelet node in my cluster.
Most of the problems I found were due to confusing and/or outdated documentation. 
This PR tries to improve the ACI provider documentation, mostly based on my experience.
> Improve ACI provider documentation

- README.md
- providers/azure/README.md
- providers/azure/aci.go
- providers/azure/client/aci/client.go
- providers/azure/client/aci/types.go
It's a little bit unclear where the docs for adding the virtual-kubelet annotation should go… I added it to the ACI readme - let me know if there's a more appropriate place for it.
> Adding support for ACI DNS name labels

- scripts/createCertAndKey.sh
I had to add no wrapping in base64 when using bash on windows  (-w0 in base64) other wise commands fails and cert isn't properly formatted
> updated createCertAndKey.sh added -w0 in base64

- providers/azure/README.md
I update the README.md file in the Azure Container Instance documentation to fix the createCertAndKey.sh lines. Added a chmod to make the file executable and also added the proper line in the shell to execute the script to allow for variables to be exported to the users current shell. By default shell script are run in a sub-shell and the environment variables will not survive the exiting of the script. Some people have added code in their .bashrc to overcome this, but we can not assume that.
I also commented out the ACI with DNS label section as that currently does not work until a new version of the virtual-kubelet for AKS is released.
> Updated ACI Documentation

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/hyperhq/hypercli/pkg/term/windows/ansi_reader.go
fix issue https://github.com/virtual-kubelet/virtual-kubelet/issues/125
```
$ go build -v
github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/hyperhq/hypercli/pkg/term/windows
vendor\github.com\hyperhq\hypercli\pkg\term\windows\ansi_reader.go:139:29: undefined: winterm.WORD
vendor\github.com\hyperhq\hypercli\pkg\term\windows\ansi_reader.go:146:24: undefined: winterm.WORD
vendor\github.com\hyperhq\hypercli\pkg\term\windows\ansi_reader.go:210:27: undefined: winterm.WORD
vendor\github.com\hyperhq\hypercli\pkg\term\windows\ansi_reader.go:210:54: undefined: winterm.DWORD
vendor\github.com\hyperhq\hypercli\pkg\term\windows\ansi_reader.go:226:34: undefined: winterm.DWORD
```
> build in git bash on windows
```
$ go build -v
$ ls virtual-kubelet.exe
virtual-kubelet.exe
```
> fix "Hypersh provider breaks the build on Windows"

- providers/aws/fargate/cluster.go
- providers/aws/fargate/container.go
- providers/aws/fargate/container_test.go
- providers/aws/provider_test.go
* Fixed a bug that caused pods without explicit resource limits to get mapped to incorrect task size.
* Addressed late code review feedback.
* Refactored e2e tests and made the test region configurable via environment variable.
> Fargate: E2E test improvements and default resource limits

- providers/aws/fargate/region.go
Fixes https://github.com/virtual-kubelet/virtual-kubelet/issues/180.
Added unit tests:
```
Running tool: /usr/local/go/bin/go test -timeout 30s github.com/virtual-kubelet/virtual-kubelet/providers/aws/fargate -run ^TestAvailableRegions$
ok  	github.com/virtual-kubelet/virtual-kubelet/providers/aws/fargate	0.037s
Success: Tests passed.
```
> Make Fargate provider available in 3 additional AWS regions

- vkubelet/vkubelet.go
"kubernetes.io/hostname" is a [well-known label for node](https://kubernetes.io/docs/reference/labels-annotations-taints/#kubernetesiohostname)
It is used in nodeSelector and nodeAffinity for pod scheduling.
In our current examples, we use nodeName to assign the pod to the VK node without the scheduler. If we use a wrong node in the pod, like #186, it's hard to troubleshoot since the pod will disappear in a few seconds.
With the hostname label, we can use the nodeSelector to ask the scheduler to assign the pod to VK node.
```
nodeSelector:
kubernetes.io/hostname: <vk-node>
```
If the node name is wrong in the pod spec, the pod will stay in the "Pending" state, and the scheduler will create the "FailedScheduling" events in `kubectl describe po <pod-name>`:
```
Events:
Type     Reason …
```
> Add the kubernetes.io/hostname label to the VK node

- providers/aws/config.go
- providers/aws/fargate.toml
Fixes https://github.com/virtual-kubelet/virtual-kubelet/issues/193.
I still need to verify with e2e tests.
~~Shall I add some unit tests for configuration file validation?~~
> [AWS Fargate] Execution role required if CloudWatch log group is specified

- providers/azure/aci.go
The Azure provider is currently using different keys in the Azure File share secrets compared to the Azure File volumes in k8s. Making them consistent.
https://docs.microsoft.com/en-us/azure/aks/azure-files-volume#create-kubernetes-secret
> Fix Azure File secret names to match k8s azureFile volume secrets

- providers/aws/fargate/region.go
Add new Fargate regions: Singapore, Sydney and Frankfurt.
> Fargate: Add new regions Singapore, Sydney, Frankfurt

- providers/azure/client/aci/client.go
The aci provider is using a quite old version of the
aci API. This PR updates it to the most recent version.
Fixes: #263
> Updating aci api version

- providers/azure/client/aci/client_test.go
- providers/azure/client/aci/types.go
This PR expands the ACI SDK to include both Readiness and Liveness Probes in `ContainerProperties` type in the ACI SDK.  Also adds `SecureValue` to the `EnvironmentVariable` type.
Fixes: #266
> ACI Provider: Adding Liveness/Readiness probes to ACI sdk

- vkubelet/apiserver.go
The exec command as extracted from the query comprises only the first
part of the command and does not include potentially supplied
parameters. E.g.,
$ kubectl exec pod -- ls -t /usr
> command: ls
This change fixes the problem by moving away from the Query.Get API.
$ kubectl exec pod -- ls -t /usr
> command: [ls -t /usr]
> Fix bug in exec command retrieval

- providers/azure/aci.go
- providers/azure/aci_test.go
ACI now supports defining liveness and readiness probes. This PR enables this in the ACI provider.
> Enabling Liveness and Readiness Probes in ACI Provider

- cmd/root.go
- providers/mock/mock.go
* read nodeName from environment variable
* using nodeName to locate config section
In this way: we can create a bunch of VK pods via StatefulSet, and expose Pod_Name to VK contains environment variable via DownwardAPI. All VK pods share a single configmap, and locate its own config parameter via it's name.
With this PR, we can use a single VK StatefulSet and a ConfigMap files to simulate a bunch of heterogenous nodes.  
example yaml files and config files are like:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
name: virtual-kubelet-set
namespace: default
spec:
serviceName: "virtual-kubelet-set"
replicas: 2
selector:
matchLabels:
app: virtual-kubelet-set
template:
metadata:
labels:
app: virtual-kubelet-set
spec:
containers:
- name: virtual-kubelet
image: virtual-kubelet:v0.3 …
```
> mock provider: read a section of config

- providers/azure/aci.go
- providers/azure/acsCredential.go
- providers/azure/client/network/profile.go
- providers/azure/client/network/profile_test.go
- providers/azure/client/network/subnet.go
- providers/azure/client/network/subnet_test.go
1. nodeName is used in setupNetworkProfile before set
2. Use vnetResourceGroup instead of AKS resource group to get VNet
3. Location is not set when creating network profile
4. networkProfile.ID is not set properly
5. Update the CreateOrUpdate functions for subnet and profile to return a pointer of the object.
6. Add the kube-proxy side car container skeleton.
> Fix several bugs in the VNET

- providers/azure/aci.go
- providers/azure/aci_test.go
1. Get the VK service account token and ca.crt to build the kubeconfig.
2. Add the kubeconfig as a Volume mounted to the kube-proxy side car container.
3. Add the Kube-Proxy side car container to the container group with the volume mount.
> Add the Kube-Proxy Side Car Container and Volume to the container group

- scripts/validate/dep.sh
This helps make sure that different versions of dep don't give different
results.
> Update dep validation to only check the vendor dir

- charts/virtual-kubelet/templates/secret.yaml
When #258 was merged, there was an omission of `env` from the values.yaml, but it was still referenced in the secrets template. This caused rendering issues. Updated the secret template, as the direction was to remove that env block.
> Remove `env` with  from secret template 

- providers/azure/aci.go
I needed Sydney. I've added centralus, eastus2,  australiaeast to match valid aci regions as [documented](https://azure.microsoft.com/en-gb/global-infrastructure/services/). I've also updated azure-cli to match.
https://github.com/Azure/azure-cli/pull/6988
> Added centralus, eastus2,  australiaeast to Azure ACI provide

- examples/busyecho.yaml
- examples/iis-pod.yaml
- examples/nanoserver.yaml
- examples/nginx-pod.yaml
- examples/pause.yaml
- vkubelet/vkubelet.go
Otherwise, the image is not backward compatible with the previous examples.
Add the old tolerations into the examples to make it backward compatible during the switch
#316
> If --taint is specified, set the taint value to empty

- Gopkg.lock
- cmd/root.go
- providers/azure/aci.go
- providers/azure/client/aci/client.go
- providers/azure/client/aci/metrics.go
- providers/azure/client/aci/types.go
- providers/azure/metrics.go
- providers/azure/metrics_test.go
- vendor/golang.org/x/sync/AUTHORS
- vendor/golang.org/x/sync/CONTRIBUTORS
- vendor/golang.org/x/sync/LICENSE
- vendor/golang.org/x/sync/PATENTS
- vendor/golang.org/x/sync/errgroup/errgroup.go
- vendor/k8s.io/kubernetes/pkg/kubelet/apis/stats/v1alpha1/types.go
- vkubelet/apiserver.go
- vkubelet/provider.go
- vkubelet/vkubelet.go
This allows hipster or metrics-server to scrape stats from VK for providers that support it.
Of course added an implementation for the Azure provider.
By default this enables a new HTTP listener on `:10255` with a `/stats/summary` endpoint.
hitting this endpoint will give a result like this:
```
{
"node": {
"nodeName": "vk-metrics",
"startTime": "2018-08-08T23:52:26Z"
},
"pods": [
{
"podRef": {
"name": "nginx",
"namespace": "default",
"uid": "4305386a-9b66-11e8-b3ec-000d3a5dae4d"
},
"startTime": "2018-08-01T23:53:34Z",
"containers": [
{
"name": "nginx",
"startTime": "2018-08-01T23:53:34Z",
"cpu": {
"time": "2018-08-09T00:14:00Z",
"usageNanoCores": 0
},
"memory": {
"time": "2018-08-09T00:14:00Z",
"usageBytes": 23470080
},
"userDefinedMetrics": null
}
],
"cpu": {
"time": …
```
> Add support fort kubelet stats summary

- vkubelet/apiserver.go
- vkubelet/vkubelet.go
Refactors how HTTP servers are started and binds them to objects that
can store the provider rather than relying on a global.
> Don't use globals for API server

- providers/azure/README.md
Regardless of whether you use the quick-start or the manual setup,
you need to run:
`az provider register --namespace 'Microsoft.ContainerInstance'`
on your account. Move up from the 'Manual' section.
> Move 'az provider register' to 'Configure your Azure account' section.

- providers/aws/provider.go
- providers/aws/provider_test.go
- providers/azure/aci.go
- providers/azure/aci_test.go
- providers/azure/client/aci/client_test.go
- providers/azure/client/aci/create.go
- providers/azure/client/aci/delete.go
- providers/azure/client/aci/get.go
- providers/azure/client/aci/list.go
- providers/azure/client/aci/logs.go
- providers/azure/client/aci/update.go
- providers/azurebatch/batch.go
- providers/azurebatch/batch_test.go
- providers/cri/cri.go
- providers/huawei/cci.go
- providers/huawei/cci_test.go
- providers/hypersh/hypersh.go
- providers/mock/mock.go
- providers/sfmesh/sfmesh.go
- providers/vic/vic_provider.go
- providers/web/broker.go
- vkubelet/apiserver.go
- vkubelet/provider.go
- vkubelet/vkubelet.go
This allows us to pass tracing, logging, and potentially other request scoped context to a provider.
> Plumb context to providers

- Dockerfile
- Makefile
Can now do something like `make VK_BUILD_TAGS=no_jaeger_exporter build`
and jaeger support will not be compiled in.
Currently there are build tags to omit each provider and tracing exporter.
> Pass go build tags from environment.

- providers/azure/aci.go
We can distinguish k8s scheduling/event-watching issue v.s. ACI creation issue.
> [ACI] Make default Container State waiting reason to be "Creating"

- cmd/taint.go
Regression bug which causes daemonset pods assign to virtual kubelet node. 
Change the default taint effect to NoSchedule.
> [VK] Change the default taint effect to NoSchedule

- providers/azure/aci.go
1. Remove the IPConfigurationProfiles check in the subnet to delegate to ACI
2. Make the network profile name a hash of the subnet ID instead of the virtual node name to avoid conflict.
> [ACI] A few bug fix for the Network Setup

- providers/azure/aci.go
- providers/azure/client/aci/client.go
- providers/azure/client/aci/client_test.go
- providers/azure/client/client.go
- providers/azure/client/network/client.go
- providers/azure/client/network/main_test.go
- providers/azure/client/resourcegroups/client.go
- providers/azure/client/resourcegroups/client_test.go
User can set the extra user agent in the ACI_EXTRA_USER_AGENT environment.
If more than one extra user agent, use whitespace to separate them.
> [ACI] Support to add extra user agent to the request

- providers/azure/README.md
Fixed typo on helm install sample. Replaced providers.azure.clientID with provider.azure.clientId so the values are correctly parsed.
> Fixed typo on helm install sample

- Gopkg.lock
- scripts/validate/dep.sh
Reasons for adding this
i) `dep check` is a lightweight alternative to the current dep validation in virtual-kubelet
ii) `dep check` provides deeper validation than the current method. For eg:- It also catches instances where new imports from an existing lib is added to the code base and the Gopkg.lock has not been updated
> Replace dep validation with dep check and resyncing Gopkg.lock

- providers/azure/aci.go
If the secret data ends with a newline, the current converter function will truncate it.
> [ACI] BugFix: secret data missing tail newline

- hack/skaffold/virtual-kubelet/base.yml
- vkubelet/pod.go
The introduction of `skaffold` - and ultimately the unfortunate fact that a permission was missing from the virtual-kubelet cluster role binding - allowed to uncover a bug in `pod.go`: when trying to delete a Pod resource from the Kubernetes API, any errors except for 404 would be swallowed (i.e. not propagated, and no log messages would be printed).
> Fix pod deletion

- .circleci/config.yml
- Makefile
- providers/cri/cri.go
I also took the liberty to tag the CRI provider to only build when on Linux. This way, `make vet` on my MacOS doesn't complain about it.
> ci: move go vet to validate check

- cmd/root.go
This reverts commit f10596562dac6623650f7871758325b9f106c420.
Makes our default worker count back to 10 now that concurrency is in
good shape.
> Revert "Use 1 worker by default"

- .circleci/config.yml
- Makefile
- README.md
This PR makes the `e2e` target:
- cleanup: delete the VK pod and delete the node from the Kubernetes API, and
- automatically builds and deploys the VK (through `skaffold`).
This way we can be sure that we have a clean environment and that we are testing the very latest changes when developing.
The motivation here is the many times I ran (locally) `make e2e` only to learn later that I hadn't build and deployed the latest changes 🤦‍♂️
> test: deploy vk when running e2e

- providers/mock/mock.go
Currently, if a pod resource is created but for some reason the mock provider does not know about it (due to an invalid resource spec or some other error), a call to `GetPodStatus` will panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x138 pc=0x107a96e]
goroutine 157 [running]:
github.com/virtual-kubelet/virtual-kubelet/providers/mock.(*MockProvider).GetPodStatus(0xc00052b830, 0x16fb320, 0xc0007bdcb0, 0xc0000c1d39, 0x7, 0xc0000c1d00, 0x10, 0x0, 0x0, 0x0)
/Users/bcustodio/Work/Go/src/github.com/virtual-kubelet/virtual-kubelet/providers/mock/mock.go:261 +0x3ce
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*Server).updatePodStatus(0xc000348000, 0x16fb320, 0xc0007bdc50, 0xc00061a700, 0x0, 0x0) …
```
> mock: do not panic on unknown pods

- vkubelet/vkubelet.go
These are no longer used since we started using the k8s client's queue.
> Remove old pod notification stuff

- test/e2e/basic_test.go
- test/e2e/framework/env.go
- vkubelet/env.go
- vkubelet/podcontroller.go
Fixes #444 
This PR fixes how `ConfigMap` and `Secret` references in a pod's `envFrom` are computed.
cc @pires
> env: fix pod envFrom processing

- website/config.toml
This PR updates the Hugo config to use the new `virtual-kubelet.io` domain as the root URL. This should fix any outstanding issues with absolute URLs.
> Update website root URL to new .io address

- website/data/providers.yaml
- website/layouts/shortcodes/providers.html
This PR updates the list of providers (see [here](https://virtual-kubelet.netlify.com/docs/providers/#current-providers)) to include a GoDoc link for each provider.
You can see a preview of the new table [here](https://deploy-preview-497--virtual-kubelet.netlify.com/docs/#providers).
> Modify providers shortcode

- cmd/root.go
- log/log.go
- log/logrus/logrus.go
- log/logrus/logrus_test.go
- log/nop.go
- providers/azure/aci.go
- providers/azure/acsCredential.go
- providers/azure/metrics.go
- providers/mock/mock.go
- trace/nop.go
- trace/opencensus/opencensus.go
- trace/opencensus/opencensus_test.go
- trace/trace.go
- vkubelet/api/helpers.go
- vkubelet/apiserver.go
- vkubelet/node.go
- vkubelet/pod.go
- vkubelet/podcontroller.go
Allows us to share data between the tracer and the logger so we can simplify log/trace handling where we generally want data to go both places.
Fixes #404
> Make tracing interface to coalesce logging/tracing

- Gopkg.lock
The tag was re-created since I force-pushed to fix up some issues with
moving git history over (b/c I originally did not move with git
history).
> Fix azure-aci vendor commit

- Gopkg.lock
- Gopkg.toml
- providers/azure/aci.go
- providers/azure/aciMock.go
- providers/azure/aci_test.go
- vendor/github.com/virtual-kubelet/azure-aci/client/aci/analytics.go
- vendor/github.com/virtual-kubelet/azure-aci/client/aci/client.go
- vendor/github.com/virtual-kubelet/azure-aci/client/aci/exec.go
- vendor/github.com/virtual-kubelet/azure-aci/client/aci/get.go
- vendor/github.com/virtual-kubelet/azure-aci/client/aci/rp.go
- vendor/github.com/virtual-kubelet/azure-aci/client/aci/types.go
This completes the GPU Support in the ACI provider. If you want to try out creating a Container with GPU resource, you can use the yaml file listed here - https://github.com/ritazh/k8s-ml/blob/master/deployments/vk-acigpu.yaml
> GPU support in ACI provider

- Dockerfile
- Makefile
- Makefile.e2e
- hack/skaffold/virtual-kubelet/Dockerfile
Allows us to make use of of make's target deps instead of re-execing
make in our build target just for custom, one-shot environment changes.
Keeps e2e bin in bin/e2e/virtual-kubelet.
> More Makefile enhancements

- providers/vic/vic_provider.go
I faced this issue when using newer golang version providers/vic/vic_provider.go:280: NewOperation call needs 1 arg but has 2 args. Indeed that is a bug that go vet reported
> providers: fix string format

- cmd/virtual-kubelet/commands/root/http.go
When setting up the http server we return a cancel function to close all
the listeners down.
The issue here is we set the cancel function to nil and thereby cause a
panic when there is an error and the `defer` attempts to call cancel.
This fix just don't set a named return value for the cancel function to
make sure we don't overwrite it with a `return nil, err`.
This ensures that the `defer` can still call `cancel()`.
Fixes #576
> Don't set cancel function to nil on error

- cmd/virtual-kubelet/commands/root/root.go
Clientset.Coordination is deprecated. We are meant to use the specific
version of the client: CoordinationV1beta1. Clientset.Coordination is
going to be removed in future versions of the client API.
> Stop using deprecated method Clientset.Coordination

- Gopkg.lock
- vkubelet/api/exec.go
Exec seems to be broken by ad6fbba806a9470fc6d3feef636ee339632c4ab8
This change basically copies what's in `remotecommand.NewOptions`, just
without the logging.
Looking at unit testing this, but the unit test was significantly more complicated with a high chance of bugs than the actual code itself.
Another option is to outfit the mock provider with some exec capabilities... maybe in a separate PR.
I manually verified this functionality against ACI.
> Fix exec parameter parsing

- providers/alibabacloud/eci.go
- providers/aws/provider.go
- providers/azure/aci.go
- providers/azurebatch/batch.go
- providers/cri/cri.go
- providers/huawei/cci.go
- providers/mock/mock.go
- providers/nomad/nomad.go
- providers/openstack/zun.go
- providers/provider.go
- providers/vic/vic_provider.go
- providers/web/broker.go
- vkubelet/api/exec.go
This removes the dependence on remotecommand in providers as well as the
need to expose provider ID's for the sake of the ExecInContainer API.
> Refactor exec interface

- Makefile
I ran into a bunch of problems running goreleasers, and
some differences with goimports. This locks the versions
to versions that appear to work.
The goimports version is newer than the latest version run
on the repo, but it matches the version of Go used on the rest of
the project.
> Use gobin to fix version numbers of tools

- cmd/virtual-kubelet/commands/root/flag.go
- cmd/virtual-kubelet/commands/root/opts.go
- cmd/virtual-kubelet/commands/root/root.go
- vkubelet/podcontroller.go
- vkubelet/vkubelet.go
This adds two concepts, where one encompasses the other.
Startup timeout is how long to wait for the entire kubelet
to get into a functional state. Right now, this only waits
for the pod informer cache for the pod controllerto become
in-sync with API server, but this could be extended to other
informers (like secrets informer).
This changes the behaviour of the virtual kubelet to wait
for the pod controller to start before registering the node.
It is to avoid the race condition where the node is registered,
but we cannot actually do any pod operations.
> Add the concept of startup timeout

- providers/azure/aci_test.go
Hi. Find a typo during use and hope to fix it.
providers/azure/aci_test.go : 
Line 91:  "convertion" is a misspelling of "conversion" 
Line 96:  "convertion" is a misspelling of "conversion"
> fix: fix a typo in azure/aci_test

- Gopkg.lock
- cmd/http.go
- vkubelet/api/exec.go
Exec seems to be broken by ad6fbba806a9470fc6d3feef636ee339632c4ab8
This change basically copies what's in remotecommand.NewOptions, just
without the logging.
(cherry picked from commit 449eb3bb7d93dbc71c1f52f48a7de6f049c76074)
> Backport: Fix exec parameter parsing (#580)

- providers/alibabacloud/eci.go
- providers/aws/fargate/cluster.go
- providers/aws/provider.go
- providers/aws/provider_test.go
- providers/azure/aci.go
- providers/azurebatch/batch.go
- providers/azurebatch/batch_test.go
- providers/cri/cri.go
- providers/huawei/cci.go
- providers/mock/mock.go
- providers/nomad/nomad.go
- providers/openstack/zun.go
- providers/provider.go
- providers/web/broker.go
- vkubelet/api/helpers.go
- vkubelet/api/logs.go
Providers must still update the implementation to actually gain any
benefit here, but this makes the provider interface a bit more sane.
> Use I/O stream for provider logs interface

- providers/mock/mock.go
There were a bunch of logging calls in the mock provider which had
formatting in them, but didn't use the log-with-formatting method.
> Fix formatting logging calls in the mock provider

- Makefile.e2e
This adds a 5 minute timeout to the end-to-end tests. The end-to-end
tests typically run in under 2 minutes. On Circle-CI the timeout is
10 minutes, at which point, Circle CI just shoots the tests in the
head so we don't get any logs.
> Add timeout to e2e tests

- .circleci/config.yml
- hack/skaffold/virtual-kubelet/pod.yml
This adds tracing to the testing to get the kubelet's logs upon
failure. In addition, it keeps track of the pods, and the node
statuses throughout the test.
> Add tracing of the kubernetes cluster during testing

- Makefile.e2e
- test/e2e/framework/framework.go
- test/e2e/framework/pod.go
- test/e2e/main_test.go
We're in effect testing the K8s scheduler logic in the test
by setting taints, as opposed to the actual VK itself. If we
want to make sure the taint is set, we can just observe the node
object.
Instead, bind to the pod to the VK node explicitly.
> Remove setting taint during e2e test

- hack/skaffold/virtual-kubelet/base.yml
- test/e2e/framework/node.go
- test/e2e/node_test.go
For some reason the kubelet tries to do things that it gets perm
denied. This changes the base.yml in the skaffold file to have
the permissions. In turn, this broke the node deletion test. So,
instead of looking for the deletion event (imperative), we wait
for the node UID to change (declarative).
> Fix permission denied warnings during tests

- .circleci/config.yml
It turns out that using gocache on circleci like this makes it
so that builds are not properly invalidated, and breaks a
whole load of things.
> Don't cache intermediate go build artifacts

- Makefile
This lets us utilize the go build cache and significantly speeds up
builds.
> Don't use `-a` on build

- Gopkg.lock
- vendor/k8s.io/kubernetes/third_party/forked/golang/expansion/expand.go
- vkubelet/env.go
- vkubelet/env_internal_test.go
Example:
env name:  FOO
value: "foo"
name:  BAR
value: "bar"
name:  FOOBAR
value: "${FOO}${BAR}" <-- should expand to: "foobar"
Added testcase for the same as well.
Change is based on kubelet_pods.go.
Simplified some of the existing code.
> Allow composing env var from existing env vars.

- cmd/virtual-kubelet/commands/root/root.go
- test/e2e/node_test.go
- vkubelet/node.go
- vkubelet/node_test.go
This moves the logic for re-creating the a missing node up into the CLI.
We can make this optional, but for now I've just preserved existing
functionality.
> Support error handler callback for node status

- vkubelet/pod.go
- vkubelet/queue.go
If we don't handle the "pod not found" case then we end up with the pod
getting re-queued over and over until the max retries are hit. It also
blocks the queue for other pod status updates for that pod
namespace/name.
> Handle not found case for status update

- hack/skaffold/virtual-kubelet/pod.yml
- test/e2e/basic_test.go
- test/e2e/framework/env.go
- test/e2e/framework/pod.go
- test/e2e/main_test.go
* Use the VKUBELET API for fetching the pods during testing, which
makes it easier to run testing without wiring up an entire cluster
* Runningpods does not require each provider to implement the
optional stats interface for testing.
* This also splits out some of the tests (Disentangles them)
* This also changes it to use the test name in the pod name.
> Use Running Pods Endpoint for testing

- node/node_test.go
Increase timeouts on test watch
This test is flakey on CI, likely because the timings are too tight, so
give a bit more time for things to complete.
Will let this run on CI a few times.
> Fix flakey node test

- cmd/virtual-kubelet/commands/root/root.go
- node/podcontroller.go
We still use it internally, but this does not need to be part of the
public API. Instead just have callers pass us the relevent listers and
we create our own resource manager.
> Remove resourcemanager from conroller public API

- cmd/virtual-kubelet/commands/root/flag.go
- cmd/virtual-kubelet/commands/root/opts.go
- cmd/virtual-kubelet/commands/root/root.go
- providers/store.go
This allows `--cluster-domain` to be passed to virtual kubelet like a
traditional kublet, and use this to generate search-domains for
`/etc/resolv.conf`
* Set default `cluster-domain` to `cluster-local` to match current kubelet
* Added an example usage for the Azure provider
* * Only apply to pods with `DNSClusterFirst` to match kubelet
* * Merge search-domains with any set in the `dnsConfig`
* * Set `ndots` to the default 5
Related: #641
Signed-off-by: Graham Hayes <gr@ham.ie>
> Allow virtual-kubelet to use cluster domain

- website/data/providers.yaml
- website/layouts/partials/home/info.html
- website/layouts/shortcodes/providers.html
On https://virtual-kubelet.io/ and https://virtual-kubelet.io/docs/#providers the links to providers documentations are incorrect. Providers moved to dedicated repositories.
Example : 
https://github.com/virtual-kubelet/virtual-kubelet/tree/master/providers/aws has been replaced by https://github.com/virtual-kubelet/aws-fargate/blob/master/README.md#readme
> Fix links to provider docs on the website

- cmd/virtual-kubelet/commands/root/node.go
- providers/mock/mock.go
- providers/provider.go
This eliminates all the one-off calls to for specific things like
`Capacity` and other things.
Instead we configure defaults in the CLI and then pass the full node
object to the provider to change as needed.
This makes sure the provider can change whatever they need to without
having to add tons of methods to the provider interface.
Closes #678
ping @gabrielhartmann
> Add provider method to pass node configuration

- README.md
* Pointed links to the README.md file in the base of each provider repo
* Removed some provider specific content from the main repos README.
Signed-off-by: Graham Hayes <gr@ham.ie>
> Update README links to providers READMEs

- Makefile
- node/pod.go
- node/pod_test.go
- Error handling was looking for a k8s error from the provider, but
providers should be using errdefs.
- Error handling was returning early if pod was not found and deleting
from k8s in all other cases.
Fixes #521
> Fix error handling for delete pod

- Makefile.e2e
Otherwise the variable is evaluated before it's even set (assuming it's
not set from the CLI).
skaffold also requires bin/e2e/virtual-kubelet to work on it's own.
Fixes #693
> skaffold target requires .SECONDEXPANSION

- node/node.go
- node/node_test.go
Thinking these maybe should either not be exposed or in a separate
package.
For 1.0 let's unexport them and we may re-introduce later.
> Unexport node update helper functions

- node/podcontroller.go
In NewPodController we validate that the rest of the config is
set to non-nil values. The provider must be non-nil as well.
> Make NewPodController function validate that provider is set

- cmd/virtual-kubelet/internal/commands/root/root.go
- node/podcontroller.go
This seems to avoid a race conditions where at pod informer
startup time, the reactor doesn't properly get setup.
It also refactors the root command example to start up
the informers after everything is wired up.
> Setup event handler at Pod Controller creation time

- node/podcontroller.go
As far as I can tell, based on the implementation in MockProvider
NotifyPods is called with the mutated pod. This allows us to
take a copy of the Pod object in NotifyPods, and make it so
(eventually) we don't need to do a callback to GetPodStatus.
> Add a little bit of documentation to NotifyPods

- node/lifecycle_test.go
- node/mock_test.go
* Fix the deletion test to actually test the pod is deleted
* Fix the update pods test to update a value which is allowed
to be updated
* Shut down watches after tests
* Do not delete pod statuses on DeletePod in mock_test
This intentionally leaks pod statuses, but it makes the situation
a lot less complicated around handling race conditions with
the GetPodStatus callback
> Array of minor fixups to lifecycle tests

- Makefile
Right now, if the tests get stuck (on CI), they are terminated
after 10 minutes. This means as well that we get 0 output about
what went wrong.
Instead, this triggers a panic after 9 minutes on CI.
> Set timeout for tests on CI to  9 minutes

- node/lifecycle_test.go
- node/mock_test.go
- node/pod_test.go
It turns out that running atomic.Read(...) in a tight loop breaks
Golang. The goroutine would never yield control over the scheduler,
so we ended up getting into a situation where the test would get
stuck forever. This moves to a different model, in which
there is a condition var, instead of atomics in loops.
> Remove usage of atomics in tests

- website/content/docs/providers.md
- website/content/docs/usage.md
- website/data/cli.yaml
- Fixed broken links mentioned in #737
- Changed `Provider` interface to `PodLifecycleHandler` interface
- Updated Virtual Kubelet CLI flags
Documentation that needs to be updated in the future:
- https://virtual-kubelet.io/docs/providers/#adding (providers no longer live in this repository)
- https://virtual-kubelet.io/docs/usage/#helm (see #582)
> Update docs on virtual-kubelet.io

- node/pod.go
- node/podcontroller.go
- node/queue.go
We introduce a map that can be used to store the pod status. In this,
we do not need to call GetPodStatus immediately after NotifyPods
is called. Instead, we stash the pod passed via notifypods
as in a map we can access later. In addition to this, for legacy
providers, the logic to merge the pod, and the pod status is
hoisted up to the loop.
It prevents leaks by deleting the entry in the map as soon
as the pod is deleted from k8s.
> Have NotifyPods store the pod status in a map

- node/lifecycle_test.go
- node/pod.go
We poll legacy providers for their pod(s) status periodically. This is because
we have no way of knowing when the pod is updated. If the pod somehow goes
missing in the provider, that state must be handled. Currently, we update
API server, and mark the pod as failed, or ignore it.
> Test pods going missing while they're running in legacy providers

- .circleci/config.yml
This caches the downloaded go modules. It invalidates them based a hash of the go.mod, and go.sum. The test step showed a reduction from 1:30 -> 1:00, and the e2e tests from 8:30 to 5 minutes.
> Cache Downloaded Go Modules

- cmd/virtual-kubelet/internal/commands/root/root.go
- node/doc.go
- node/lifecycle_test.go
- node/pod_test.go
- node/podcontroller.go
- node/podcontroller_test.go
Adds Done() and Err() to pod controller
Allows callers to wait for pod controller exit in addition to readiness.
This means the caller does not have to deal handling errors from the pod
controller running in a gorutine since it can wait for exit via `Done()`
and check the error with `Err()`
> Add methods to wait for pod controller exit and errors

- trace/opencensus/opencensus.go
Correctly expand the log args
Fix #775
> Fix log format

- node/lifecycle_test.go
- node/mock_test.go
- node/pod.go
- node/pod_test.go
- node/podcontroller.go
- node/podcontroller_test.go
This moves from forcefully deleting pods to deleting pods in a
graceful manner. It keeps track of the pods that were deleted,
so the provider doesn't get duplicate pod deletions unnecessarily.
It only retries deletion if the pod's graceperiod was reduced.
> Do not delete pods in a non-graceful manner

- node/lifecycle_test.go
- node/mock_test.go
- node/pod.go
- node/pod_test.go
- node/podcontroller.go
- node/sync.go
This brings back support for sync providers by wrapping them in a
provider that handles async notifications.
This way we don't break the existing API.
> Re-add support for sync providers

- node/pod.go
current version VK can not show event when we use `kubectl describe pod xxx`, though pod has failed. e.g. A pod failed due to not found image, when I use `kubectl get pod xxx`, I get as follow:
But when  `kubectl describe pod xxx`, it just shows 
Fix #796
> add some events to pod

- cmd/virtual-kubelet/internal/commands/root/flag.go
- cmd/virtual-kubelet/internal/commands/root/http.go
- cmd/virtual-kubelet/internal/commands/root/opts.go
- node/api/exec.go
- node/api/server.go
Make exec timeout configurable
See 
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/config/types.go#L165
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L2296
kubelet also allows to change default steamIdleTimeout, so I think it's to reasonable to make it configurable
Fix: https://github.com/virtual-kubelet/virtual-kubelet/issues/791
> Make exec timeout configurable

- node/api/helpers.go
When calling GetContainerLogs(), a type check is performed to see if the
http.ResponseWriter supports flushing. However, Flush() in http.Flusher
does not return an error, therefore the type check will always fail.
Fix the flushWriter helper interface so flushing the writer will work.
> Use correct Flush() prototype from http.Flusher

- node/api/server.go
I found a BUG in virtual-kubelet:
users trying to do pod exec with WebSocket will end with 405, while pod exec with SPDY will be ok.
The reason is:
WebSocket usually starts handshake with a http request of 'GET'
pod exec handler in virtual-kubelet only register 'POST' method
PS：code of pod exec handler in virtual-kubelet actually suport both WebSocket and SPDY
> add 'GET' method to pod exec handler, so it can support websocket

- node/pod.go
Check pods status deep equal before update. If we do not check it, we would update pod status frequently and reach the qps limit quickly.
> Check pods status deep equal before update

- node/api/exec.go
This was an unintentional breaking change in
0bdf7423037e0ccefb794c8b5f570137c65ce864
A timeout of 0 doesn't make any sense, so use the old values of 30s as a
default.
> Fix stream timeout defaults

- scripts/validate/check_version.sh
We had locked to version v1.17.6 when this script was released. At the time,
it was also the current stable release, and what was presented by the
github API. It turns out the Github API does not present all tags. This
changes it to fetch the annotated tag from the upstream repo.
> Fix kubernetes version dependency checking script

- node/node.go
There's a (somewhat) common case we can get into where the node
status update loop is busy while a provider is trying to send
a node status update. Right now, we block the provider from
creating a notification in this case.
> Make node status updates non-blocking

- node/node.go
- node/node_test.go
As described in the patch itself, there is a case that if a node is updated out of
band (e.g. node-problem-detector (https://github.com/kubernetes/node-problem-detector)),
we will overwrite the patch in our typicaly two-way strategic patch for node status
updates.
The reason why the standard kubelet can do this is because the flow goes:
apiserver->kubelet: Fetch current node
kubelet->kubelet: Update apiserver's snapshot with local state changes
kubelet->apiserver: patch
We don't have this luxury, as we rely on providers making a callback into us
in order to get the most recent pod status. They do not have a way
to do that merge operation themselves, and a two-way merge doesn't
give us enough metadata.
In order to work around this, we perform a three-way merge on behalf of
the user. We do …
> Introduce three-way patch for proper handling of updates

- node/api/pods.go
This follows suit with other hanlders and returns a NotImplemented
http.HandlerFunc when the lister is nil.
> Fix running pods handler on nil lister

- node/api/server.go
To allow users to attach both the pod and metrics handlers to the same mux, use "/stats/summary" as the pattern in AttachPodMetricsRoutes. Otherwise, if mux.Handle() is called again for the same pattern, it will panic, and this is what happens in node-cli due to https://github.com/virtual-kubelet/node-cli/pull/27 calling both AttachPodRoutes() AttachPodMetricsRoutes() with the same mux.
> Use /stats/summary for metrics handler

- node/pod.go
- node/pod_test.go
- node/podcontroller.go
This solves the race condition as described in
https://github.com/virtual-kubelet/virtual-kubelet/issues/836.
It does this by checking two conditions when the possible race condition
is detected.
If we receive a pod notification from the provider, and it is not
in our known pods list:
1. Is our cache in-sync?
2. Is it known to our pod lister?
The first case can happen because of the order we start the
provider and sync our caches. The second case can happen because
even if the cache returns synced, it does not mean all of the call
backs on the informer have quiesced.
This slightly changes the behaviour of notifyPods to that it
can block (especially at startup). We can solve this later
by using something like a fair (ticket?) lock.
> Solve the notification on startup pod status notification race condition

- node/api/server.go
Backports #853 
--- 
If both the metrics routes and the pod routes are attached to the same
mux with the pattern "/", it will panic. Instead, add the stats handler
function to PodHandlerConfig and set up the route if it is not nil.
> Add GetStatsSummary to PodHandlerConfig

- node/nodeutil/filter.go
- node/nodeutil/filter_test.go
- node/podcontroller.go
- node/podcontroller_test.go
This allows users who have a shared informer that is *not* filtering on
node name to supply a filter for event handlers to ensure events do not
fire for pods not scheduled to the node.
> Support custom filter for pod event handlers

- go.mod
- node/mock_test.go
- node/node.go
- node/node_ping_controller.go
- node/node_test.go
- node/waitable_int_test.go
This moves the job of pinging the node provider into its own
goroutine. If it takes a long time, it shouldn't slow down
leases, and vice-versa.
> Move node pinging to its own goroutine

- node/node.go
This takes a somewhat hamfisted approach at dealing with lease
conflicts. This can happen if "someone" changes the lease underneath
us. Again, this should happen rarely, but it can happen (And does
happen in production systems).
Signed-off-by: Sargun Dhillon <sargun@sargun.me>
> Delete and recreate lease on conflict

- node/node.go
- node/node_ping_controller.go
Change the place where we set the defaults for node ping
and node status interval. This problem manifested itself
by the node ping interval being 0 when it was set to
the default.
This makes two changes:
1. Invalid ping values, and ping timeouts will not
allow VK to start up
2. We set the default values very early on in creation
of the node controller -- where all the other values
are set.
Signed-off-by: Sargun Dhillon <sargun@sargun.me>
> Fix node ping interval code / default setting code

- node/node.go
This fixes a small logic bug in the leases code for checking is owner
references are not set correctly, and makes it so that we properly
log when owner references are set, but not set to the node that
is "us".
> Fix logging when leases are mis-set

- website/content/docs/usage.md
closes #545
Replaces external and internal verbiage with more commonly used "on Kubernetes" and "external to Kubernetes"
Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>
> Remove confusing internal external verbiage

- node/node.go
- node/node_test.go
- node/podcontroller_test.go
There were some (additional) bugs that were easy-ish to introduce
by interleaving the provider provided node, and the server provided
updated node. This removes the chance of that confusion.
> Create stronger separation between provider node and server node

- test/e2e/README.md
Hi there,
I am currently in the process of creating a provider (just for fun, nothing serious) and I am following the e2e docs (thank you so much for providing e2e tests 💯).
I found that the embedded go code for the provider is not actually compilable, so I thought a quick fix might spare others a few minutes of research time 👍
> docs(e2e): make example e2e.go compilable

- cmd/virtual-kubelet/internal/commands/root/root.go
- cmd/virtual-kubelet/internal/provider/mock/mock.go
- internal/test/suite/suite.go
- internal/test/suite/suite_test.go
- node/node.go
- node/nodeutil/client.go
- test/e2e/suite.go
- Create a clientset
- Setup pod informer filters
- Setup node lease client
- Add V2 naive node provider for accepting node status updates and use that to wait for node readiness in e2e tests
This splits up some stuff from #859
> Add helpers for common setup code

- node/nodeutil/client.go
The `NewNonInteractiveClientConfig`(`k8s.io/client-go@v0.18.4/tools/clientcmd/merged_client_builder.go`)  will be called inside the `ClientConfig()`(line 33), whose second argument is `config.overrides.CurrentContext`. Using `nil` here will cause `nil pointer dereference` runtime error.
> Bug: when initialzing vk, use empty clientcmd.ConfigOverrides instead of nil

- internal/podutils/env.go
- internal/podutils/env_internal_test.go
- node/pod.go
- test/e2e/basic.go
This creates a new package -- podutils. The env var related code
doesn't really have any business being part of the node package,
and to create a separation of concerns, faster tests, and just
general code isolation and cleanliness, we can move the env
var related code into this package. This change is purely hygiene,
and not logic related.
> Move env var code into its own package

- cmd/virtual-kubelet/internal/provider/mock/mock.go
"alpha.service-controller.kubernetes.io/exclude-balancer" has been removed since v1.19.0, we should ensure the new label "node.kubernetes.io/exclude-from-external-load-balancers" is added for virtual node:
```
// labelNodeRoleExcludeBalancer specifies that the node should not be considered as a target
// for external load-balancers which use nodes as a second hop (e.g. many cloud LBs which only
// understand nodes). For services that use externalTrafficPolicy=Local, this may mean that
// any backends on excluded nodes are not reachable by those external load-balancers.
// Implementations of this exclusion may vary based on provider. This label is honored starting
// in 1.16 when the ServiceNodeExclusion gate is on.
labelNodeRoleExcludeBalancer = …
```
> Ensure label node.kubernetes.io/exclude-from-external-load-balancers is added to virtual node

- Makefile
This adds a target that allows the users to run goimports
across the entire repo.
> Add fmt target

- Makefile
This sets KUBEBUILDERA_ASSETS only for envtest. No need to leak
the variable throughout the tests. In addition, it makes it easier
to figure out how to run the tests yourself on command line.
> Do not export KUBEBUILDER_ASSETS variable

- internal/test/vk_envtest/env_test.go
This configures the global logger the same as the local logger,
and adds the test name. It also uses the logger with the test
context as the context logger.
> In envtest, configure the logger correctly

- internal/lock/monitor.go
- internal/lock/monitor_test.go
- node/node_ping_controller.go
Refactor the way that the that node_ping_controller works
This moves node ping controller to using the new internal lock
API.
The reason for this is twofold:
* The channel approach that was used to notify other
controllers of changes could only be used once (at startup),
and couldn't be used in the future to broadcast node
ping status. The idea idea is here that we could move
to a sync.Cond style API and only wakeup other controllers
on change, as opposed to constantly polling each other
* The problem with sync.Cond is that it's not context friendly.
If we want to do stuff like wait on a sync.cond and use a context
or a timer or similar, it doesn't work whereas this API allows
context cancellations on condition change.
The idea is that as we have more controllers that act as centralized …
> Refactor node ping controller

- .golangci.yml
- cmd/virtual-kubelet/internal/commands/providers/provider.go
- cmd/virtual-kubelet/internal/commands/root/tracing_register_jaeger.go
- cmd/virtual-kubelet/internal/provider/mock/mock.go
- internal/podutils/env.go
- node/node_test.go
- node/podcontroller.go
- trace/opencensus/opencensus_test.go
This removes the directive from .golangci.yml to disable all linters,
and fixes the relevant bugs / issues that are exposed.
> Enable all linters by default

- Makefile
- cmd/virtual-kubelet/internal/commands/root/root.go
- node/env_test.go
- node/lease_controller_test.go
- node/lease_controller_v1.go
- node/main_test.go
- node/node.go
- node/node_ping_controller.go
- node/node_test.go
- node/nodeutil/client.go
This refactors the v1 lease controller. It makes two functional differences
to the lease controller:
* It no longer ties lease updates to node pings or node status updates
* There is no fallback mechanism to status updates
> This adds the v1 lease controller

- internal/queue/queue.go
I made a whoops and capitalized the queue name.
> Fix key name in log entry

- log/klogv2/klogv2.go
- log/klogv2/klogv2_test.go
Previously:
```
I0112 13:06:38.331656    2784 klogv2.go:55] Installing [policyrcd-script-zg2], to prevent installed daemons from starting%!(EXTRA map[string]interface {}=map[])
I0112 13:06:38.331697    2784 klogv2.go:55] Checking if ["policyrcd-script-zg2"] is installed%!(EXTRA map[string]interface {}=map[])
I0112 13:06:38.558750    2784 klogv2.go:55] Using internal/external IP addresses: [192.168.64.15 192.168.64.15]/map[]
I0112 13:06:38.559154    2784 klogv2.go:51] [No certificates found, disabling GetContainerLogs] map[]
E0112 13:06:38.566320    2784 klogv2.go:67] [TLS certificates not provided, not setting up pod http server] map[caPath:]
I0112 13:06:38.566624    2784 klogv2.go:51] [Initialized] map[node:systemk operatingSystem:Linux provider:systemd watchedNamespace:]
I0112 …
```
> log: fix klog depth and output format

- README.md
It redirects me to `https://github.com/virtual-kubelet/virtual-kubelet/blob/master/virtualkubelet-dev@lists.cncf.io` which is 404 page. I change to mail list page instead.
> Update mailing list link

- node/pod_test.go
- node/podcontroller.go
I would say this solves a somewhat worrying / urgent bug.
If you share a ratelimiter between workqueues, it breaks.
WQ1: Starts processing item (When)
WQ1: Fails to process item (When)
WQ1: Fails to process item (When)
WQ1: Fails to process item (When)
--- At this point we've backed off a bit ---
WQ2: Starts processing item (with same key, When)
WQ2: Succeeds at processing item (Forget)
WQ1: Fails to process item (When) ---> THIS RESULTS IN AN ERROR
This results in an error because it "forgot" the previous
rate limit.
CC: @cwdsuzhou
> Split out rate limiter per workqueue

- go.mod
- go.sum
- internal/queue/queue.go
- internal/queue/queue_test.go
- node/pod.go
- node/podcontroller.go
Replace golang workqueue with our own
This is a fundamentally different API than that of the K8s workqueue
which is better suited for our needs. Specifically, we need a simple
queue which doesn't have complex features like delayed adds that
sit on "external" goroutines.
In addition, we need deep introspection into the operations of the
workqueue. Although you can get this on top of the K8s workqueue
by implementing a custom rate limiter, the problem is that
the underlying rate limiter's behaviour is still somewhat
opaque.
This basically has 100% code coverage.
@cpuguy83 You might like this better because it doesn't spawn a ton of daemon threads in the background. 
I want y'all to look at the algorithm / approach and make sure you don't fundamentally disagree with it.
> Add Alternative Workqueue Implementation

- node/env_test.go
- node/lifecycle_test.go
- node/pod.go
- node/podcontroller.go
We had added an optimization that made it so we dedupe pod status updates
from the provider. This ignored two subfields that could be updated along
with status.
Because the details of subresource updating is a bit API server centric,
I wrote an envtest which checks for this behaviour.
> Fix pod status update

- node/podcontroller.go
This seems to be a typo where we erroneously double-queue a deletion,
but one without the "key".
CC: @cwdsuzhou
> Remove errant double queue

- internal/queue/queue.go
- internal/queue/queue_test.go
- node/lifecycle_test.go
- node/pod.go
- node/podcontroller.go
- node/queue.go
Our current retry policy is naive and only does 20 retries. It is
also based off of the rate limiter. If the user is somewhat aggressive in
rate limiting, but they have a temporary outage on API server, they
may want to continue to delay.
In facts, K8s has a built-in function to suggest delays:
https://pkg.go.dev/k8s.io/apimachinery/pkg/api/errors#SuggestsClientDelay
Signed-off-by: Sargun Dhillon <sargun@sargun.me>
> Add the ability to dictate custom retries

- cmd/virtual-kubelet/internal/provider/mock/mock.go
- cmd/virtual-kubelet/internal/provider/provider.go
- internal/test/e2e/framework/stats.go
- node/api/stats.go
- node/api/statsv1alpha1/README.md
- node/api/statsv1alpha1/types.go
- test/e2e/basic.go
This drops another dependency on k8s.io/kubernetes.
This does have the unfortunate side effect that implementers will now
get a compile error until they update their code to use the new type.
Just as a note:
The stats types have moved to k8s.io/kubelet, however the stats types
are only there as of v1.20.
Currently we support older versions than v1.20, and even our go.mod
imports from v1.19.
For now we copy the types in. Later we can remove the type defs and
change them to type aliases to the k8s.io/kubelet types (which prevents
another compile time issue).
Anything relying on type assertions to determine if something implements
this method will, unfortunately, be broken and it will be hard to notice
until runtime. We need to make sure to call this out in the release
notes.
Fixes #946
> Copy stats types from upstream.

- README.md
Fixes a typo ("provides") and also replaces "listed above" with a link to the list. Which had moved below, as it happens.
> Fix non-linked reference to Providers in Usage

- cmd/virtual-kubelet/internal/commands/root/tracing_register_jaeger.go
jaeger's config `Endpoint` has been deprecated:
```go
// Options are the options to be used when initializing a Jaeger exporter.
type Options struct {
// Endpoint is the Jaeger HTTP Thrift endpoint.
// For example, http://localhost:14268.
//
// Deprecated: Use CollectorEndpoint instead.
Endpoint string
...
```
so fix must specify check condition.
> fix jaeger deprecated config

- .circleci/config.yml
- Makefile
- Makefile.e2e
- internal/expansion/expand_test.go
- node/lifecycle_test.go
This adds an override for `go test` so in CI we can use `gotestsum` which outputs junit formatted results which will be consumed by circleci.
> Output test results in junit and export to circle

- cmd/virtual-kubelet/internal/commands/root/root.go
- node/node.go
- node/node_test.go
- node/nodeutil/controller.go
This makes a controller that handles the startup for the node and pod
controller.
Later if we add an "api controller" it can also be added here.
This is just part of reducing some of the boiler plate code so it is
easier to get off of node-cli.
---
Moves some more stuff from #859
> Move some boiler plate startup logic to nodeutil

- node/lease_controller_v1.go
- node/sync.go
Found that this caused a panic after many many test runs.
It seems like we should have returned early since the pingResult is nil.
We don't want to update a lease when ping fails.
> Return early on ping error

- cmd/virtual-kubelet/internal/commands/root/flag.go
Client-go v0.19 needs to be used with klog/v2, but the flagSet of virtual-kubelet still uses klog (v1), which will cause if client-go needs to be debugged, setting the klog flag has no effect
> Change klog flag version to v2

- node/node.go
With this one line, vk fails to build against k8s 1.24 libs.
The comment says:
// Deprecated: ClusterName is a legacy field that was always cleared by
// the system and never used; it will be removed completely in 1.25.
Seems to be removed in 1.24 though.
----
There are other PRs like #1001 and #1373, but all I really need is to make sure it compiles when used as a library.
> Removed deprecated node Clustername

- .github/workflows/codeql-analysis.yml
These are extremely slow and probably very expensive for someone.
We don't need these running on PR's which have constant pushes, rebases,
etc.
The activity on the repo is slow enough we can fix-up things after
codeql runs on master.
> Only run codeql on pushes to master, not pr's

- .github/workflows/codeql-analysis.yml
Codeql requires write access to security-events, but our default action token (rightly) only has read permissions.
This adds the explicit request for write access.
Relevant issue: https://github.com/github/codeql-action/issues/464#issuecomment-828811531
> codeql: Add explicit permissions

- README.md
Since `virtual-kubelet` is mainly intended to be used as a library, this should help people to find its documentation easier.
Generated on [pkg.do.dev's badge page](https://pkg.go.dev/badge/).
> README.md: add go.dev badge

- cmd/virtual-kubelet/internal/provider/mock/mock.go
- internal/kubernetes/remotecommand/attach.go
- node/api/attach.go
- node/api/server.go
- node/nodeutil/provider.go
Extended virtual kubelet API with the "Attach" subresource.
- Attach funtionality to remote commands
- Attach functionality API handler
- update PodHandlerConfig to also manage attach method
- update Provider interface to also have an AttachToContainer property
> Add support for Attach API functionality

- Makefile.e2e
I was trying to play around with `virtual-kubelet` and I see that there is a check for kubectl context against docker-desktop and minikube.  
I tend to like to use `kind` so I am attempting to use it for virtual-kubelet testing.  
This is my first issue I discovered when running `make`.  
Generally, kind has a context that is the following `kind-$KIND-CLUSTER-NAME$` so I do a regular expression check against context.
> Support Kind in Makefile check

- node/podcontroller.go
This PR adds three new methods to the PodController struct. These methods return the current length of the SyncPodsFromKubernetes, DeletePodsFromKubernetes, and SyncPodStatusFromProvider queues, respectively. These methods will provide valuable insights into the queue sizes, which can be used for monitoring and performance tuning.
At Netflix, we are working on tuning the PodController rate limiter and we need insights into the queue size.
> feat: Add methods to get length of PodController queues

- node/nodeutil/controller.go
Currently the virtual node is created during virtual kubelet start up. We hit a situation that the virtual node might be deleted by kubernetes control plane due to lost heartbeat. The virtual node won't be recovered until we restart the virtual kubelet.
This PR adds an error handler to nodeController so it has a chance to recreate the node when the virtual node is gone.
> Add error handler to recreate virtual node when it's deleted

- internal/queue/queue.go
- node/podcontroller.go
This change is a follow-up to https://github.com/virtual-kubelet/virtual-kubelet/pull/1145 based on our experience using the exposed queue len for observability at Netflix.
The existing `Len()` func is useful for instrumentation, but its current implementation includes unprocessed items and those currently being processed. As a result, it's challenging to discern from our metrics whether we're hitting a rate limit or simply viewing the number of items being processed.
To address this I've added separate getter functions to expose the count of unprocessed items in the queue and the items currently under processing separately. We intend to create separate metrics for these values.
> Expose queue unprocessed and items being processed len

- README.md
The smallest of fixes. Happened to see it while reading the docs.
> docs(README): typo in PodLifecycleHandler

- log/slog/slog.go
Adds support for [slog](https://pkg.go.dev/log/slog) as a logger within virtual-kubelet. It implements the `log.Logger` interface for `slog` in a similar style to the other implementations.
> add support for slog logger

- node/nodeutil/controller.go
- node/pod.go
- node/pod_test.go
- node/podcontroller.go
Currently, VK attempts to resolve downward APIs before calling the provider's CreatePod or UpdatePod implementation. However, there are valid reasons a provider may want to do downward API resolution themselves.
This is a logical first step to expose downward resolution utilities to providers as discussed [here](https://github.com/virtual-kubelet/virtual-kubelet/issues/1032)
> Allow providers to skip VK downward API resolution

- .gitignore
- Makefile
This PR supersedes #1265, adding `envtest`, setting up the environment with `setup-envtest`.
In the [docs](https://pkg.go.dev/sigs.k8s.io/controller-runtime/tools/setup-envtest) they say to use the `latest` version with Go 1.24+, but I've pinned the [`v0.0.0-20250604165838-d6126d850224`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/tools/setup-envtest@v0.0.0-20250604165838-d6126d850224) version, released few days ago (Jun 4, 2025).
Closes #1265
> test: replace kubebuilder with envtest (2)
